### ISSUE TITLE
論理演算子について

### ISSUE THREAD

**Issue by good1luck21** [sice11/practice#11]
https://github.com/sice11/practice/blob/f6a87b5dfd5105ded4d27997b267d11b033e16b6/JavaScript/LESSON/05_29/lesson0529_2sample.html#L18-L23

```javascript
if(true){
// trueのときに処理が走る。
}

if(!true){
// falseのときに処理が走ります。
}
```

下記に参考リンク添付しますので、ご参考にして頂ければと思います！
https://udemy.benesse.co.jp/development/web/javascript-if-else.html
上記リンクの「JavaScript if〜elseにおける論理演算子not（!）について」に説明があります！

宜しくお願い致します！

**Comment by sice11** [comment]
ありがとうございます。
notの意味だったのですね。
