### ISSUE TITLE
【jQuery】親要素・子要素の適応について

### ISSUE THREAD

**Issue by sice11** [sice11/practice#13]
https://github.com/sice11/practice/blob/540d733741e1a4b587943a1e2c58065307f31ec4/jQuery/TASK/review/re.html#L34

上記のコマンドを作成して、
class = "nintendo"を親とするclass = "gameboy"をも背景色を黄色にしたいと考えています。

ですが、
上記コマンドに対し、
```
$(".nintendo").parent().css("background","yellow");
```
やclass = "gameboy"など、新たにクラスを作成したりもしてみたのですが、
うまくいきませんでした。
（もともとは）
https://github.com/sice11/practice/blob/540d733741e1a4b587943a1e2c58065307f31ec4/jQuery/TASK/review/re.html#L18
https://github.com/sice11/practice/blob/540d733741e1a4b587943a1e2c58065307f31ec4/jQuery/TASK/review/re.html#L19
の部分が、
```
<li>gemeboyCOLOR</li>
<li>gemeboyADVANCE</li>
```
どのようにすれば
class = "nintendo"以下の部分を背景色　黄色にできますか？

![無題](https://user-images.githubusercontent.com/61615289/83598774-8a7f3200-a5a5-11ea-8087-d7c5b2e64f17.png)

**Comment by sice11** [comment]
期待値は
上図にある
gameboyCOLOR
gameboyADVANCE
も黄色にすること

**Comment by good1luck21** [comment]
- htmlいじらない方法
```javascript
$(function(){
        $(".gameboy").css("background", "yellow");
})
```

- htmlをいじる方法
```html
<div class = "nintendo">
        gameboy
        <li class = "gameboy">gemeboyCOLOR</li>
        <li class = "gameboy">gemeboyADVANCE</li>
</div>
```

やり方としては2通りかなと思います。
今の通りpタグを使いたいのであればJqueryで新しく定義してあげる。

その方法でないのであれば、pタグをdivタグにしてあげて範囲を広げてあげれば黄色に出来ます！。

**Comment by sice11** [comment]
pタグをdivタグに変更することが想定していた回答でしたので、
そちらを採用しました。
ありがとうございます。

```
        <div class = "nintendo">
            gameboy
            <li class = "gameboy">gemeboyCOLOR</li>
            <li class = "gameboy">gemeboyADVANCE</li>
        </div>
```

```
        $(function(){
            $(".nintendo").css("background","yellow");
        });
```

![無題](https://user-images.githubusercontent.com/61615289/83610068-fe2b3a00-a5b9-11ea-8fc0-2c54e3239a6a.png)

**Comment by sice11** [comment]
以下いただいた参照箇所
https://www.cyber-bridge.jp/blog/html-css/1746/
