### ISSUE TITLE
【jQuery】changeメソッドを活用して、selectの値を変える

### ISSUE THREAD

**Issue by sice11** [sice11/practice#15]
select A と B を用意して、
Aの値によって、自動的にBの値を変える動作をしたいと考えています。

changeを活用して行いたいのですが、どのようにすればいいでしょうか？

具体的な動作は
shop のidがふられているもので、
「ヨドバシ」を選択すると、
group のidがふられているものから、
「ヨドバシグループ」
が、自動選択。
その他は「ビックカメラグループ」に
自動選択されるようにしたいです。

**Comment by sice11** [comment]
select部分
```
    <select id = "shop" name = "shopName">
        <option value = "yodobashi">ヨドバシ</option>
        <option value = "sofmap">ソフマップ</option>
        <option value = "bigcamera">ビックカメラ</option>
    </select>

    <select id = "group" name = "groupName">
        <option value = "yodobashiGP">ヨドバシグループ</option>
        <option value = "bigcameraGP">ビックカメラグループ</option>
    </select>
```

change部分
```
            $("#group").change(function(){
                if($("#shop").val() != "yodobashi"){
                    $("#group").val("bigcameraGP")
                }else{
                    $("#group").val("yodobashiGP")
                }
            });
```

コードの全体↓
https://github.com/sice11/practice/blob/master/jQuery/STUDY/index14.html#L33

**Comment by good1luck21** [comment]
jqueryのidの記述が違います。

```javascript
$("#shop").change(function(){
    if($("#shop").val() != "yodobashi"){
        $("#group").val("bigcameraGP")
    }else{
        $("#group").val("yodobashiGP")
    }
});
```
これで動きますー。

**Comment by sice11** [comment]
changeは、参照先（shop）と変更先（group）があった場合、
最初の( )には、参照先を入れる。

**Comment by good1luck21** [comment]
https://github.com/sice11/practice/blob/15b3c641c59df818a6369476bc40ee31837dd915/jQuery/STUDY/index14.html#L23-L24

ちなみに上記２行の変数は使用していないので、削除しておいたほうがいいですね。
プログラムというのは上から順番に実行されていくので、行数が多くなるとその分処理に時間がかかるので、
出来るだけ削減できるところに関しては削減しましょう！

**Comment by sice11** [comment]
確かに使われてないですね。
修正しました。
ありがとうございます。
