### ISSUE TITLE
Noneについて・クラス内での呼び出しについて

### ISSUE THREAD

**Issue by sice11** [sice11/practice#18]
https://github.com/sice11/practice/blob/master/Python/TASK/free/RPG.html#L9
上記の設計書をもとに、RPGのような動作をするものを作成しようと考えています。
直近として、登場人物に主人公と敵がいます。
それぞれのステータスを一度classにて作成しようと考えています。

質問①
https://github.com/sice11/practice/blob/master/Python/TASK/free/RPG2.py
上記コードを出力した際に出てくる
「None」はなぜ出てくるのでしょうか？
![無題](https://user-images.githubusercontent.com/61615289/84096226-5fc92980-aa3c-11ea-92e0-5a6d0caf3bfb.png)

質問②
classを主人公と敵用に実行する際、
```
hiro = Status("hiro",120,random.randint(20,40),attribute)
```
このように実行しています。
可能であれば、
```
hiro = Status("hiro",120,attack,attribute)
```
のようにスマートに記述できればいいなと考えています。
ですが、classの中身を
```
        self.attack = random.randint(20,40)
```
と記述しなおすと、エラーが出てしまいます。

主人公と敵のattackのrandom範囲は変えようと思っていたので、
このままでもいいといえばいいのですが、もう少しいい書き方があれば教えてください。
（せっかくなので、attackだけrandom範囲を変えたいということもあり、classの継承とかも考えてはいたのですが…）

**Comment by good1luck21** [comment]
- Noneについて
Pythonではメソッドの戻り値としてデフォルトでNoneが設定されています。
今回の場合はそもそもcallメソッドでプリントしているのに、その後インスタンス化した後に、print(hiro())とやってしまっていることで、callメソッド内のデフォルトの戻り値が出力されてしまったという内容になります。
![image](https://user-images.githubusercontent.com/12671938/84100050-0534cb00-aa46-11ea-93a2-5c211014414c.png)
参考のリンクをお送りしますので、確認してみてください！
https://teratail.com/questions/148585

- Classについて
適用と主人公用で分けたいということですかね？
それとも引数で渡している `random.randint(20,40)` これを変数化したいってことですかね？
ちょっと内容が掴みきれなかったためご確認頂ければと思います。

**Comment by sice11** [comment]
・Noneについて
　そうだったんですね。
　また、printを二回も記述していたことは失念していました。

・Classについて
　敵と主人公とで別にしようかと考えています。
主人公
```
random.randint(20,40)
```
敵
```
random.randint(10,30)
```
のようにしようとしています。

また、うまく言えませんが、
変数にしたいというより、メソッドとして、呼び出せるようにしたいと考えています。

**Comment by sice11** [comment]
classについて、
勘違いがあったようです。

うまく記載できませんが、
Statusという設計書をもとに、
主人公と敵の各々の値を決めようとしていました。

そのためには、Statusを継承し、
新たに各々作成しなおさなければならないと考えていました。

ですが、
主人公と敵の値を決めるのに、わざわざ継承する必要もなく、
ここにあるように、
```
hiro = Status("hiro",120,random.randint(20,40),attribute)
```
として、記述し、
攻撃力が欲しければ、
```
print(hiro.attack)
```
のようにすればよかったんですね。

**Comment by good1luck21** [comment]
```python
import random

class Player:
    def __init__(self, name):
        self.name = name

    def attack(self, enemy):
        print(self.name + "は、" + enemy + "に" + attack_num() + "のダメージを与えた！")

class Wizard(Player):
    def attack(self, enemy):
        print(self.name + "は、" + enemy + "に炎を放ち" + attack_num() + "のダメージを与えた！")

# 攻撃を共通メソッドでまとめる。
def attack_num():
  damage = str(random.randint(20,40))
  return damage

hero = Player("勇者")
warrior = Player("戦士")
wizard = Wizard("魔法使い")

party = [hero, warrior, wizard]
for member in party:
    member.attack("ラスボス")
```

```shell
P49944:Downloads takeru.sato$ python3 lesson2.py
勇者は、ラスボスに20のダメージを与えた！
戦士は、ラスボスに26のダメージを与えた！
魔法使いは、ラスボスに炎を放ち25のダメージを与えた！
P49944:Downloads takeru.sato$
```
実行するとこんな感じでそれぞれ出ます！

こんな感じのことがやりたいのかなって思ったんですが違いますかね？

**Comment by sice11** [comment]
そうです。
これをどちらかのhpがゼロになるまで繰り返し、
最後にresultとして、どちらが勝ったかを出力しようとしています。

まだまだ途中ですが、
また完成や詰まった部分があれば、
アドバイスお願いいたします。
