### ISSUE TITLE
ソースレビュー

### ISSUE THREAD

**Issue by good1luck21** [sice11/practice#33]
https://github.com/sice11/practice/blob/b58bdf0dac19a9876a98a93dbb0cbe19a4c42aa6/Ruby/TASK/shopping.rb#L21-L40

* list 関数
- [ ] 入力した商品名は上書きされているが本来なら商品一覧を出したほうがいいのでは？
- [ ] 値段は足すだけでいいのでhashの必要はない。

- アドバイス
   - 文字列は配列
   - 数字はそのまま足すもしくは引く。

**Comment by sice11** [comment]
https://github.com/sice11/practice/blob/30381e6c5dc9b923a974f6af9a6180c9caf3279d/Ruby/TASK/shopping_edit.rb#L21-L40

こういった感じのニュアンスでしょうか？

**Comment by good1luck21** [comment]
いや、値段を入れるinput_valueという変数を配列に格納するのではなく、
input_value = input_value + gets.chomp.to_i みたいな感じでそのまま足しちゃう感じですね。
っで今まで商品を入力してくださいというのがあったかなと思うので、それをwant_listの中に入れてあげて、
入力した商品はこちらですと行った形で一覧を出し、最終的に合計金額を出すって感じが良いんじゃないかなと思います

**Comment by sice11** [comment]
https://github.com/sice11/practice/blob/8c3dd59fa11106687e270598ead2bc95d0950c9e/Ruby/TASK/shopping_edit.rb#L21-L44

このような感じでいかがでしょうか？

また、予算オーバー時の処理も付け足してみました。
https://github.com/sice11/practice/blob/8c3dd59fa11106687e270598ead2bc95d0950c9e/Ruby/TASK/shopping_edit.rb#L46-L57

**Comment by sice11** [comment]
while ( )ではなく、
while でOK
↑while スペース

**Comment by sice11** [comment]
ex)
```
 while(inputs_flag2) 
```
の部分を
```
 while inputs_flag2
```
